
include $(PXPRPC_SOURCE_DIR)/native_pipe/core/make-config.mk

pipecoretest.exe:pipecoretest.c build_pxprpc_pipe
	$(CC) -o pipecoretest.exe $(CFLAGS) $(PXPRPC_PIPE_CFLAGS) pipecoretest.c $(PXPRPC_PIPE_LDFLAGS)





