
#pragma once

//"__gen_pxprpc_rtbridge_mod_include_list2026" is generated by cmake
#include <__gen_pxprpc_rtbridge_mod_include_list2026.hpp>

#if PXPRPC_RTBRIDGE_HAVE_JNI_H
#include "../java/jnibridge.cpp"
#endif

typedef void (*pxprpc_rtbridge_mod_init_func)();

//"__gen_pxprpc_rtbridge_mod_entry_list2026.hpp" is generated by cmake
static pxprpc_rtbridge_mod_init_func pxprpc_rtbridge_mod_init[] ={
    #include <__gen_pxprpc_rtbridge_mod_entry_list2026.hpp>
    nullptr
};

