
#pragma once

//"__gen-mod-include.txt" is generated by cmake
#include "__gen-mod-include.txt"

#if PXPRPC_RTBRIDGE_HAVE_JNI_H
#include "../java/jnibridge.cpp"
#endif

typedef void (*pxprpc_rtbridge_mod_init_func)();

//"__gen-mod-entry.hpp" is generated by cmake
static pxprpc_rtbridge_mod_init_func pxprpc_rtbridge_mod_init[] ={
    #include "__gen-mod-entry.txt"
    nullptr
};

